### ISSUE TITLE
[作業報告]

### ISSUE THREAD

**Issue by wakame-tech** [WorldRIZe/wr-app#19]
作業する度にここのコメント欄に作業時間と内容を報告してください

#### 例
3/7 2時間
- XXXX画面を作成中
- YYYYを修正

**Comment by wakame-tech** [comment]
3/7 3時間
- Firebaseセットアップ
- 設定画面作成

**Comment by yoshiki301** [comment]
3/17 2時間

* フレーズ詳細画面仮組み

**Comment by wakame-tech** [comment]
Slack上での作業報告へ移行します
