### ISSUE TITLE
コラム画面作成

### ISSUE THREAD

**Issue by wakame-tech** [WorldRIZe/wr-app#26]
# Overview
## 画面
- タスク / TOP
	カテゴリ毎に画像リンク
- タスク / カテゴリ記事一覧
	Webへのリンク
	
# Reference
Google Docs参照

**Comment by yoshiki301** [comment]
途中までやったところでプルリク出しました。 #33

**Comment by wakame-tech** [comment]
コンフリクト解決して一旦developmentとマージしときました。
引き続きプルして作業お願いしたい

- 検索欄は他の画面と共通になりそうだから今はなしで
- `コラム/TOP`から遷移した`コラム/記事一覧`はデザインがまだなので仮でよいです
