### ISSUE TITLE
NoteでフレーズのachivedのUXの変更

### ISSUE THREAD

**Issue by YuhoShimizu** [worldrize/wr-app#300]
- 移動した旨のトースト
- チェックしてから

> 最初から緑のチェックを押したら移動するのではなくて、全部ブランクにして、ユーザーが押したら緑になって他のページに行ったタイミングでフレーズを移動した方が良い。
わからなかったら連絡して！

**Comment by hamadakafu** [comment]
beta版以降にノートのフレーズ画面のUI改修でまとめて修正したい

**Comment by YuhoShimizu** [comment]
了解どす

**Comment by hamadakafu** [comment]
いつの間にかやってた
