### ISSUE TITLE
FAV issue

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#330]
![IMG_47308E04F9D0-1](https://user-images.githubusercontent.com/71547619/94330559-cdf42500-0008-11eb-982e-5e1d289a2ce9.jpeg)

ここでのハートが機能していない（外すことは可能

**Comment by world-rize** [comment]
確認したら全部のハートが機能していないかも
外すことはできる

**Comment by wakame-tech** [comment]
一時的なものです
