### ISSUE TITLE
bookmark&fav

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#331]
![IMG_689E89F028A6-1](https://user-images.githubusercontent.com/71547619/94330582-23c8cd00-0009-11eb-8534-8717c6afd9df.jpeg)
Lesson画面からのハートが機能していない
ブックマークもノートに移した事がわかるように緑色とか色を付けたい

**Comment by hamadakafu** [comment]
要相談、というのも
ノートにあるフレーズは編集できてしまうので、もとのレッスンのフレーズと全く異なるものにできてしまう。
ポップアップか下からぴょこっとトーストっぽいやつか。。。

**Comment by world-rize** [comment]
なるほどね、でも一応これをベースに編集するから別にいいんじゃないかなとも思う。。

**Comment by hamadakafu** [comment]
ぴょこっとで知らせます
ベータのあとでここらへん細かく決めたい
https://github.com/worldrize/wr-app/issues/337

**Comment by hamadakafu** [comment]
やっぱりアニメーション使います
