### ISSUE TITLE
新しいpubやCI/CDの検証のためのMinimum Project

### ISSUE THREAD

**Issue by wakame-tech** [worldrize/wr-app#354]
- [x] codemagicでflavorの切り替え
- [x] semantic versionのお試し
- [ ] ~semantic releaseをブランチ1本でやる~
  - できないので、2本でやる
  - ボタンをトリガーにする
  - [workflow dispatch] (https://github.com/actions/starter-workflows/blob/dacfd0a22a5a696b74a41f0b49c98ff41ef88427/automation/manual.yml)
- [ ] github actionのmacosビルド
- [ ] bitrise
- [x] 各種新しいライブラリ

**Comment by hamadakafu** [comment]
とりあえずplaygroundがあるので一旦close
