### ISSUE TITLE
クラッシュ

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#376]
クラッシュするところ一覧
フレーズ画面入る時　（これが1番クラッシュする）
テストの時
ブックマークでnoteに移す時

が落ちやすいかな
全体的に落ちてしまう印象なのでこれを改善次第拡散します

**Comment by hamadakafu** [comment]
https://sentry.io/organizations/worldrize/issues/1904845969/?project=5418385&query=is%3Aunresolved

- [ ] 何個かエラー報告されてるので確認する

**Comment by world-rize** [comment]
お願いします

**Comment by hamadakafu** [comment]
## 気になるところ
10/28 10:16:00.939 午後 | outlined_flag | getAppInfo 1000msかかってる。長すぎ

**Comment by hamadakafu** [comment]
duplicated #395
