### ISSUE TITLE
ログイン時のたーとポリシーとプライバシーポリシーのリンクの修正

### ISSUE THREAD

**Issue by hamadakafu** [worldrize/wr-app#386]
# ❓ 概要

# 📚 参考

**Comment by hamadakafu** [comment]
@world-rize 
terms of service押したら以下のリンクで問題ない???

https://world-rize.com/wr-english-terms-of-use/

![IMG_FA045961C4B7-1](https://user-images.githubusercontent.com/34128227/97516606-cbedff00-19d6-11eb-99b1-f190ddde9ff7.jpeg)

**Comment by world-rize** [comment]
それで🙆‍♂️
