### ISSUE TITLE
ログインor sign up時の表示

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#387]
ログインor sign up時に日本語になってるから英語にしてほしい、、、

確か
名前
メールアドレス
パスワードのところ

外国人の友達になか見てもらうときにわからんって言われてしまった。

Androidが使えない可能性ありなのであした友達のスマホで検証する

**Comment by wakame-tech** [comment]
一時的な確認のためにi18nするのは作業コスト高いのでとりあえず併記する形で行きます(`e.g. 名前/Name`).

**Comment by world-rize** [comment]
お願いします

**Comment by wakame-tech** [comment]
とりあえず完了
