### ISSUE TITLE
ノート機能で削除をどうにかする

### ISSUE THREAD

**Issue by hamadakafu** [worldrize/wr-app#393]
ノートでフレーズを削除した際に突然消えるので、ワンクッションほしい

2つ案がある
- ~もとに戻す方法 google drive~
- ~チェックボックスの見た目でわかりやすくするか~

**Comment by world-rize** [comment]
デザインが変更されるので実装が簡単な方で大丈夫です

**Comment by hamadakafu** [comment]
achievedに移動するかしないかのダイアログを出すようにします
