### ISSUE TITLE
太字のミス

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#396]
<img width="457" alt="Screen Shot 2020-10-29 at 12 31 01 am" src="https://user-images.githubusercontent.com/71547619/97442500-08414100-197e-11eb-9a78-6b1d3477a4ac.png">
こっちのミスで二箇所太字になってます。

google driveで　restaurant 16　
すでに訂正済み

ココ訂正お願いします
申し訳ない

**Comment by wakame-tech** [comment]
修正しました
