### ISSUE TITLE
B版アンケート　相談

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#399]
https://forms.gle/cbx45Azc9bDvwEdS8

今回はアンケートになるべく多く回答して欲しいのでアンケートを出すタイミングを変えて欲しい
三回テスト後じゃ遅いのかなって

テスト一回終わったらでいいと思う！
添付画像みたいにバツを左上においてしたは回答するだけの方が上がりそう、回答率が

<img width="790" alt="Screen Shot 2020-10-29 at 1 47 37 pm" src="https://user-images.githubusercontent.com/71547619/97519402-50e41300-19ed-11eb-8d30-ac30e19d2e50.png">

**Comment by world-rize** [comment]
今あるやつを簡単に変更できたりする？
既存のアンケートで行くところの画面

**Comment by hamadakafu** [comment]
@wakame-tech 
デザインfigmaにあげといたので実装するだけ
