### ISSUE TITLE
クラッシュリスト　0.6.4(7)

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#409]
phrase detailに行く画面で必ず落ちる
testをするときはいを押したあと
Favからphrase detailに行くとき「

時間が経つと安定して落ちなくなった

**Comment by hamadakafu** [comment]
@wakame-tech 
https://github.com/worldrize/wr-app/blob/6b38fe3db65be4435c04565739bf881842364174/lib/run_app_with_flavor.dart#L222-L228

ここらへん
- audioPlayerのバージョンを上げる
- voicePlayserのスコープを狭くする

**Comment by hamadakafu** [comment]
https://github.com/florent37/Flutter-AssetsAudioPlayer
