### ISSUE TITLE
新しいノートが作れない

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#440]
![IMG_4AEF5773D5AB-1](https://user-images.githubusercontent.com/71547619/99245022-0836b180-2857-11eb-81b8-6fb052259acd.jpeg)

こんな表示が出てくる

**Comment by wakame-tech** [comment]
ノート数制限のエラーだね
表示がフレンドリーじゃないからエラー見やすくしたい

**Comment by wakame-tech** [comment]
ノートのタイトルが作れないのは機能がないので別issue立てます
