### ISSUE TITLE
匿名アカウントで始められるようにする

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#485]
無料ダウンロードは匿名アカウントでサインインなし
アップグレード時または後（有料版）にログイン・サインアップ必須

## TODO
- [x] dynamic linkのprdの設定
- [x] dynamic linkのenv化

https://firebase.google.com/docs/auth/android/email-link-auth

https://firebase.flutter.dev/docs/auth/usage/#verifying-a-users-email

https://medium.com/dev-genius/firebase-flutter-dynamic-links-step-by-step-guide-630402ee729b

https://medium.com/firebase-developers/dive-into-firebase-auth-on-flutter-email-and-link-sign-in-e51603eb08f8

**Comment by world-rize** [comment]
![IMG_9510](https://user-images.githubusercontent.com/71547619/104464021-92f11e00-5606-11eb-8c52-645d3ff482e9.jpg)
参考画像です

**Comment by takemuseki** [comment]
セキュリティルールどうなるの
